# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0005_auto_20170321_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='user_registered_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
