# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0006_auto_20170321_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rank', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='type.Competition')),
                ('required_competition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='required_competition', to='type.Competition')),
            ],
        ),
    ]
