# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0007_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 10, 29, 6, 808339)),
            preserve_default=False,
        ),
    ]
