# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0008_competition_registration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='type.Competition'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='required_competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requires', to='type.Competition'),
        ),
    ]
