# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0009_auto_20170325_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='user_registered_number',
        ),
    ]
