# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0010_remove_competition_user_registered_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvement',
            name='started_conpetition',
            field=models.BooleanField(default=False),
        ),
    ]
