# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0014_auto_20170328_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvement',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
    ]
