# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0015_involvement_wpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='text',
        ),
        migrations.AddField(
            model_name='competition',
            name='text',
            field=models.ManyToManyField(to='type.Text'),
        ),
    ]
