# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0016_auto_20170329_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.TextField(default=''),
        ),
    ]
