# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0017_user_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvement',
            name='finished_competition',
            field=models.BooleanField(default=False),
        ),
    ]
